name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone JADX Collaboration
        uses: actions/checkout@v4
        with:
          path: jadx-collaboration

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Clone JADX
        uses: actions/checkout@v4
        with:
          repository: skylot/jadx
          path: jadx

      - name: Build JADX
        run: ./jadx/gradlew copyArtifacts

      - name: Move jadx.jar
        run: mv ./jadx/build/jadx/lib/jadx-dev-all.jar ./jadx-collaboration/jadx.jar

      - name: Test JADX Collaboration
        run: ./jadx-collaboration/gradlew test
