name: Build Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Clone JADX
        uses: actions/checkout@v4
        with:
          repository: skylot/jadx

      - run: pwd
      - run: ls

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -i
